const data = {
  products: [
    {
      _id: "1",
      name: "Grey Flowered",
      category: "Duvet Covers",
      image: "/images/products/greyFlowery.jpg",
      brand: "",
      price: 10000,
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Cotton with 300tc",
    },
    {
      _id: "2",
      name: "7Pc Utensil Set",
      category: "Kitchenware",
      image: "/images/products/utensil_set.jpg",
      brand: "Arshia",
      price: 7000,
      rating: 4.9,
      numReviews: 14,
      countInStock: 0,
      description: "Arshia 7pc utensil set with stand.",
    },
    {
      _id: "3",
      name: "Ceramic Cooking Pots",
      category: "Cookware",
      image: "/images/products/ceramic_hover.jpg",
      brand: "Arshia",
      price: 28000,
      rating: 5.0,
      numReviews: 6,
      countInStock: 4,
      description: "Ceramic cookware non stick and non scratch",
    },
    {
      _id: "4",
      name: "Vaccum Cleaner",
      category: "Other Appliances",
      image: "/images/products/vaccum.jpg",
      brand: "Arshia",
      price: 18000,
      rating: 4.5,
      numReviews: 16,
      countInStock: 0,
      description: "Arshia vaccum cleaner.",
    },
  ],
};

export default data;
